### PR TITLE
sim results post-processing

### PR DESCRIPTION
**Pull request by yongqx**
This is for cause_model only and will be updated after we add intervention component.

### CODE REVIEW

**Comment by collijk** [comment]
Can you convert your notebook to a script that produces the plots and writes them to files?  If not, let's chat in coworking about how to.  Notebooks do not play well with version control.

**Comment by yongqx** [comment]
TO DO:
1. Try convert notebook into .py script. (Abie would like to have notebook saved somewhere!)
2. I currently compare cause (state) `susceptible_tb_positive_hiv` results from sim to GBD `hiv_aids_resulting_in_other_diseases` results. Try add `susceptible_tb_positive_hiv` and `ltbi_positive_hiv` then compare.

**Comment by aflaxman** [comment]
There are some extensions for diffing notebooks.  @collijk would something like this address your concerns? https://nbdime.readthedocs.io/en/latest/

**Comment by collijk** [comment]
I'll clean up this and https://github.com/ihmeuw/vivarium_csu_ltbi/pull/21/files this evening and turn them into little command line utilities.

**Comment by yongqx** [comment]
> I'll clean up this and https://github.com/ihmeuw/vivarium_csu_ltbi/pull/21/files this evening and turn them into little command line utilities.

Thanks James!

**Pull request merged**
